# -*- coding: utf-8 -*-
"""CPSC_2200_DLP_chapter02_mathematical-building-blocks(ChristianLee).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B0HasG4Y-GfX4lRC1a-4QQQGA4YQAyH6

# Yale University

# CPSC 2200 Introduction to Data Analysis and Machine Learning for Humanities and Social Sciences

**Instructor**: Sohee Park

**TF**: George Typaldos

**ULA**: Kenneth Shui

Department of Computer Science

This is a notebook generated for CPSC 2200, a companion notebook for the book [Deep Learning with Python, Third Edition](https://www.manning.com/books/deep-learning-with-python-third-edition). For readability, it only contains runnable code blocks and section titles, and omits everything else in the book: text paragraphs, figures, and pseudocode.

**If you want to be able to follow what's going on, I recommend reading the notebook side by side with your copy of the book.**

The book's contents are available online at [deeplearningwithpython.io](https://deeplearningwithpython.io).

**Learning Objectives:**

This module covers

* A first example of a neural network (Classify handwriting digits)
* Tensors and tensor operations
* How neural networks learn via backpropagation
"""

!pip install keras keras-hub==0.21.1 --upgrade -q   # keras-hub version

import os
os.environ["KERAS_BACKEND"] = "tensorflow"

# @title
import os
from IPython.core.magic import register_cell_magic

@register_cell_magic
def backend(line, cell):
    current, required = os.environ.get("KERAS_BACKEND", ""), line.split()[-1]
    if current == required:
        get_ipython().run_cell(cell)
    else:
        print(
            f"This cell requires the {required} backend. To run it, change KERAS_BACKEND to "
            f"\"{required}\" at the top of the notebook, restart the runtime, and rerun the notebook."
        )

"""## The mathematical building blocks of neural networks

### A first look at a neural network
"""

from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# print shape of train_images
print(train_images.shape)

# print len of train_images
print(len(train_images))

# How do train labels look like?
print(train_labels[:20], train_labels.shape, train_labels.dtype)

# print shape of test_images
print(test_images.shape)

# print len of test_images
print(len(test_images))

# How do test labels look like?
print(test_labels[:20], test_labels.shape, test_labels.dtype)

"""We have checked that we have 60,000 training images and lables, and 10,000 test images and labels.

Let's sneak peak a test image and its label. To display a test image and the label, let's import matplot lib and display a image.
"""

import matplotlib.pyplot as plt

plt.imshow(test_images[0])
plt.title(f"Label: {test_labels[0]}")
plt.axis('off')
plt.show()

"""**The network architecture**

We build a network - again, remember that **you are not expected to understand everything about this example yet**. You will learn the details in the future chapters.
"""

import keras
from keras import layers

model = keras.Sequential(
    [
        layers.Dense(512, activation="relu"),
        layers.Dense(10, activation="softmax"),
    ]
)

"""The core building block of neural network is the *layer*. Some data goes in to a layer, and it comes out it a more useful form. Specifically, layers extract `representations` out of the data fed into them - representations that are more meaningful for the problem at hand. Most of deep learning consists of chaining together simple layers that will implement a form of pregressive *data distillation*. A deep learning model is like a sieve for data processing, made of a succession of increasingly refined data filters - the layers.

Our model consists of a sequence of two `Dense` layers, which are densely connected (also called *fully connected*) neural layers. The second (and last) layer is a 10-way softmax classification layer, which means it will return an array of 10 probability scores (summing to 1). Each score will be the probability that the current digit image belongs to one of our 10 digit classes.

To make the model ready for training, we need to pick three more things as part of the `compilation` step:

* `An optimizer` - The mechanism through which the model will update itself based on the training data it sees, so as to improve its performance.

* A `loss function` - How the model will be able to measure its performance on the training data, thus how it will be able to steer itself in the right direction.

* `Metrics to monitor during the training and testing` - We will look at accuracy (the fraction of the images that were correctly classified).

**The complilation step**
"""

model.compile(
    optimizer="adam",                           # The mechanism that model will update itself based on training data, to improve perfromance.
    loss="sparse_categorical_crossentropy",     # How the model will be able to measure the performance on the training data
    metrics=["accuracy"],                       # We will look at accuracy - the fraction of images correctly classified.
)

"""**NOTE)** The exact purpose of the loss function and the optimizer will be made clear throughout
the next two chapters.

**Preparing the image data**

Initially, our training images are stored in an array of shape (60000, 28, 28) of type `unit8` with values in the range of [0, 255]. We will transform it into a float array of shape (60000, 28*28) with values between 0 and 1.
"""

train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

"""**"Fitting" the model**

We are ready to train the model. In Keras, it is done via a call to the model's `fit()` method - we ***fit*** the model to it training data.
"""

# fit the model using train images, labels, 5 epochs and batch_size=128
model.fit(train_images, train_labels, epochs = 5, batch_size =128)

"""Two quantities are displayed during the training: the `loss`, and the `accuracy`.

As we have a trained model, we can use it to predict class probabilities for new digits - images that were not part of the training data, images in test set (`test_images`) in our example.

**Using the model to make predictions**
"""

# take the first 10 test_images
test_digits = test_images[0:10]
# we perform a prediction using model.predict()
predictions = model.predict(test_digits)
#display the first prediction

"""The probability for digit 7 is the highest. You can check the prob. using argmax () method, which returns 7, indicating that the model classifies the first test image as 7."""

# use argmax() to check which digit has the highest probability
predictions.argmax()

predictions[0][7]

"""Now, we can compare the actual label, in test_labels."""

test_labels[0]

"""**Evaluating the model on new data**"""

# we use model.evaluate() to compute average accuracy over the entire test set
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")

"""### Data representations for neural networks

In the previous example, we started from data stored in  multidimensional NumPy arrays, also called `tensors`. In general, all current machine learning systems use tensors as their basic data structure. Tensors are fundamental to the field.

A tensor is a container for data - usaully numerical data. So it is a container for numbers.

#### Scalars (rank-0 tensors)

A tensor that contains only one number is called a `scalar` (or scalar tensor, or rank-9 tensor, or 0D tensor). In NumPy, a `float32` or `float64` number is a scalar tensor.

You can display the number of axes of a NumPy tensor via the `ndim` attribute; a scalar tensor has 0 axes (`ndim` == 0). The number of axes of a tensor is also called its `rank`.
"""

import numpy as np
# create an array with a single int element
x = np.array(10)
x

# use the .ndim attribute to print dimension number of array
np.ndim(x)

"""#### Vectors (rank-1 tensors)

An array of numbers is called a `vector`, or rank-1 tensor, or 1D tensor. A rank-1 tensor is said to have exactly one axis.
"""

# create an int vector
x = np.array([12, 3, 6, 14, 7])
x

x.ndim

"""#### Matrices (rank-2 tensors)"""

# create an int matrix
x = np.matrix(7)
x.ndim

"""#### Rank-3 tensors and higher-rank tensors"""

x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
x.ndim

"""#### **Key attributes**

A tensor is defined by three key attributes:

* ` Number of axes (rank)` - For instance, a rank-3 tensor has three axes, and a matrix has two axes. This is also called the tensor's `ndim` in Python libraries such as NumPy or TensorFlow.
* `Shape` - This is a tuple of integers that describes how many dimensions the tensor has along each axis. For instance, the previous matrix example has shape  (3,5), and the rank-3 tensor example has shape (3, 3, 5). A vector has a shape with a single element, such as (5,), whereas a scalar has an empty share, ().
* `Data type (usually dtype in Python libraries)` - This is the type of the data contained in the tensor; for instance, a tensor's type can be `float16`, `float21`, `float64`, `unit8`, and so on. In TensorFlow, you are also likely to come across `string` tensors.

Let's look back at the data we processed in the `MNIST` example.
"""

from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

train_images.ndim

train_images.shape

train_images.dtype

import matplotlib.pyplot as plt

digit = train_images[4]
plt.imshow(digit, cmap=plt.cm.binary)
plt.show()

train_labels[4]

"""#### Manipulating tensors in NumPy

**Slicing**

Selecting specific elements in a tensor is called tensor **slicing**.
Let’s look at the tensor-slicing operations you can do on NumPy arrays.
The following example selects digits #10 to #100 (#100 isn’t included) and puts them
in an array of shape (90, 28, 28):
"""

# select train_images from #10 to #100
my_slice = train_images[10:100]
my_slice.shape

my_slice = train_images[10:100, :, :]   #Equivalent to the previous example.
my_slice.shape

my_slice = train_images[10:100, 0:28, 0:28] #Also equivalent to the previous example
my_slice.shape

my_slice = train_images[:, 14:, 14:]
my_slice.shape

# slice train_images to select all of them along the 1st dimension and then
# crop each one by taking pixels from index 7 up to (not including) 7th pixel
# from the end (for both height and width dimensions)
my_slice = train_images[:, 7:-7, 7:-7]
my_slice

"""#### The notion of data batches

In general, the first axis (axis 0, because indexing starts at 0) in all data tensors you’ll
come across in deep learning will be the samples axis. In the MNIST example, “samples”
are images of digits.
In addition, deep learning models don’t process an entire dataset at once; rather,
they break the data into small “batches,” or groups of samples with a fixed size. Concretely,
here’s one batch of our MNIST digits, with a batch size of 128:
"""

batch = train_images[:128]

"""The next batch:"""

# take batch 128 to 256
batch = train_images[128:256]

"""And the nth batch:"""

n = 3
batch = train_images[128 * n : 128 * (n + 1)]

"""When considering such a batch tensor, the first axis (axis 0) is called the batch axis (or
batch dimension). You’ll frequently encounter this term when using Keras and other
deep learning libraries.

#### Real-world examples of data tensors

The data you’ll manipulate will almost always fall into one of the following
categories:

* **Vector data** - Rank-2 tensors of shape (samples, features), where each sample is a vector of numerical attributes ('features`)
* **Timeseries data or sequence data** - Rank-3 tensors of shape (samples, timesteps, features), where each sample is a sequence (of lenth `timesteps`) of feature vectors.
* **Images** - Rank-4 tensors of shapes (sample, heights, width, channels), where each sample is a 2D grid of pixels, and ech pixel is represented by a vector of values ("channels")
* **Video** - Rank-5 tensors of shape (samples, frames, height, width, channels), where each sample is a sequence (of lenth frames) of images

##### Vector data

* An actual data set of people, where we consider each person's age, gender, and income. Each person can be characterized as a vector of 3 values, and thus entire data set of 100,000 people can be stored in a rank-2 tensor of shape **(100000,3)**.
* A dataset of text documents, where we represent each document by the counts of how many times each word appears in it (out of a dictionary of 20,000 common words). Each document can be encoded as a vector of 20,000 values (one count per word in the dictionary), and thus an entire dataset of 500 documents  an be stored in a tensor of shape **(500, 20000)**.

##### Timeseries data or sequence data

Whenever time matters in your data (or the notion of sequence order), it makes sense to store it in a rank-3 tensor with and explicit time axis. Each sample can be encoded as a sequence of vectors (2 rank-2 tensor), and thus a batch of data will be encoded as a rank-3 tensor.

The time axis is always the second axis (axis of index 1) by convention. Here are some examples.

* **A dataset of stock prices**: Every minute, we store the current price of the stock, the highest price in the past minute, and the lowset price in the past minute. Thus, every minute is encoded as a 3D vector, an entire day of trading is encoded as a matrix of shape (390, 3) (there are 390 minutesin a trading day), and 250 days' worth of data can be stored in a rank-3 tensor shape (250, 390, 3). Here each sample would be one day's worth of data.

* **A dataset of tweets**: We encode each tweet as a sequence of 280 characters out of an alphabets of 128 unique characters. In this setting, each character can be encoded as a binary vector of  size 128. A data set of 1 million tweets can be stored in a tensor of shape (1000000, 280, 128)

##### Image data

Images typically have three dimensions: height, width, and color depth.
* A batch of 128 grayscale images of size 256x256 could thus be stored in a tensor of shape (128, 256, 256, 1), or (128, 1, 256, 256) - *channels-first*

* A batch of 128 color images could be stored in a tensor of shape (128, 256, 256, 3), or (128, 3, 256, 256) for *channels-first*.

##### Video data

A batch of four video clips, each 60-seconds, 144x256 sampled at 4 frames per second (4*60  = 240 frames for 60 seconds has shape (4, 240, 144, 256, 3): 106,168,320 values.
"""

# validate the above computation using python
print(4 * 240 * 144 * 256 * 3)

"""### The gears of neural networks: Tensor operations

#### Element-wise operations
"""

def naive_relu(x):
    assert len(x.shape) == 2        # x is rank-2 Numpy tensor.
    x = x.copy()                    # Avoid overwriting the input tensor.
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

def naive_add(x, y):
    assert len(x.shape) == 2        # x and y are rank-2 Numpy tensors.
    assert x.shape == y.shape
    # implement naive_add similar to naive_relu
    # by elementwise adding y to x
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = x[i, j] + y[i, j]
    return x

"""In practice, when dealing with NumPy arrays, these operations are available as
well-optimized built-in NumPy functions.
"""

import time

x = np.random.random((20, 100))
y = np.random.random((20, 100))

t0 = time.time()
for _ in range(1000):
    z = x + y
    z = np.maximum(z, 0.0)
print("Took: {0:.2f} s".format(time.time() - t0))

t0 = time.time()
for _ in range(1000):
    z = naive_add(x, y)
    z = naive_relu(z)
print("Took: {0:.2f} s".format(time.time() - t0))

"""#### Broadcasting

Our earlier naive implementation of naive_add only supports the addition of rank-2
tensors with identical shapes. But in the Dense layer introduced earlier, we added a
rank-2 tensor with a vector. What happens with addition when the shapes of the two
tensors being added differ?

Broadcasting lets you perform operations on tensors of different shapes by implicitly expanding them to be compatible — saving memory and code complexity.

When possible, and if there’s no ambiguity, the smaller tensor will be broadcast to
match the shape of the larger tensor. Broadcasting consists of two steps:

1. Axes (called broadcast axes) are added to the smaller tensor to match the ndim of
the larger tensor.
2. The smaller tensor is repeated alongside these new axes to match the full shape
of the larger tensor.

Let’s look at a concrete example. Consider X with shape (32, 10) and y with shape
(10,):
"""

import numpy as np

X = np.random.random((32, 10))      # X is a random matrix with shape (32, 10).
y = np.random.random((10,))         # y is a random vector with shape (10,).

"""First, we add an empty first axis to y, whose shape becomes (1, 10):"""

y = np.expand_dims(y, axis=0)       # The shape of y is now (1, 10).

"""Then, we repeat y 32 times alongside this new axis, so that we end up with a tensor Y
with shape (32, 10), where Y[i, :] == y for i in range(0, 32):
"""

Y = np.tile(y, (32, 1))      # Repeat y 32 times along axis 0 to obtain Y with shape (32, 10).

"""At this point, we can add X and Y because they have the same shape.

In terms of implementation, no new rank-2 tensor is created because that would be
terribly inefficient. **The repetition operation is entirely virtual**: it happens at the algorithmic
level rather than at the memory level. But thinking of the vector being repeated
32 times alongside a new axis is a helpful mental model.
"""

X = np.ones((3,5))
y = np.ones((5,))
print(X)
print(y)
print(X+y)                     # We can add X and y because the broadcasting is done virtually.

"""Here’s what a naive implementation
would look like:
"""

def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    x = x.copy()
    # implement naive_add by adding
    # y[j] to x[i, j]
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

import numpy as np

x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)

"""#### Tensor product

**product of two vectors, x and y**
It computes as follows:
"""

x = np.ones((3,))
y = np.ones((3,))
print(x)
print(y)
print(np.matmul(x,y))

x = np.random.random((32,))
y = np.random.random((32,))

# use np.matmul to multiply x, y
z = np.matmul(x, y)
# use the @ operator
z = x @ y

def naive_vector_product(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    z = 0.0
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

"""You’ll have noticed that the **product between two vectors is a scalar** and that only vectors
with the same number of elements are compatible for this operation.

**matrix vector product**

You can also take the product between a matrix x and a vector y, which returns a vector
where the coefficients are the products between y and the rows of x.
"""

# create matrix x: 2 x 3, initialized to 1
x = np.ones((2, 3))
# create vector y: 3 x 1, initialized to 1
y = np.ones((3, 1))
# compute matrix-vector product of x, y

# Using np.matmul
product = np.matmul(x, y)

# Using the @ operator
# product = x @ y

print(x)
print(y)
print(product)

"""You implement
matrix vector product as follows:
"""

def naive_matrix_vector_product(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z

"""You could also reuse the code we wrote previously,`naive_vector_product`, which highlights the relationship
between a matrix-vector product and a vector product:
"""

def naive_matrix_vector_product(x, y):
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        # multiply row i from x with vector y
        # use slicing to get row i from x
        row_x = x[i, :]
        # and call naive_vector_product
        z[i] = naive_vector_product(row_x, y)
    return z

"""**matrix product**"""

def naive_matrix_product(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    z = np.zeros((x.shape[0], y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            # take row i from x with slicing
            row_x = x[i, :]
            # take column j from y with slicing
            column_y = y[:, j]
            # store to z[i, j] the result of naive_vector_product
            # of row_x and column_y
            z[i, j] = naive_vector_product(row_x, column_y)
    return z

"""Matrix dot-product diagram

<img src = 'https://drive.google.com/uc?id=1xCZw_QlCmHQyQM_Gaz4EWrM5GODUHI9A' width =500 >

Examples
"""

import numpy as np
x = np.ones((2,3))
y = np.ones((3,1))
# initialize a matrix x[2,3] and a vector y[3,1]

print(x)
x.shape

print(y)
y.shape

# calculate the product of x, y

product = np.matmul(x,y)
product

"""#### Tensor reshaping"""

# use .reshape to reshape train_images into shape (60000, 28 * 28)
train_images = np.reshape(train_images, (60000, 28 * 28))

x = np.array([[0., 1.],
              [2., 3.],
              [4., 5.]])
x.shape

# reshape x into shape (6, 1)
x = x.reshape((6,1))
x

x # reshape  x into shape (2, 3)
x = x.reshape((2,3))
x

x = np.zeros((300, 20))
# transpose x via np.transpose
x = np.transpose(x)
x.shape

"""#### Geometric interpretation of tensor operations

* **Translation**: Adding a vector to a point will move the point by a fixed amount in a fixed direction.

* **Rotation**: A counterclokwise rotation of a 2D vector by an angle theta.

* **Scaling**: A vertical and horizonal scaling of the image  

* **Linear Transform**: A dot product with an arbitrary matrix.  Scaling and rotation are linear tranforms.

* **Affine transform**: Combination of a linear transform (achieved via a dot product with some matrix) and a translation (ahieved by a vector addition)  

* **Dense layer with activation**: An important observation about affine transforms
is that if you apply many of them repeatedly, you still end up with an affine transform
(so you could just have applied that one affine transform in the first place). As a consequence,
**a multilayer neural network made entirely of Dense layers without activations
would be equivalent to a single Dense layer.**

Tensor addition represens the action of translating an object (moving the object without distorting it)

#### A geometric interpretation of deep learning

### The engine of neural networks: Gradient-based optimization

#### What's a derivative?

#### Derivative of a tensor operation: The gradient

#### Stochastic gradient descent

#### Chaining derivatives: The Backpropagation algorithm

##### The chain rule

##### Automatic differentiation with computation graphs

### Looking back at our first example
"""

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255

# Create a keras.Sequential model with 2 Dense layers
# 1st layer will use 'relu' activation
# 2nd layer 'softmax' activation
model = keras.Sequential(
    [
        layers.Dense(512, activation="relu", input_shape=(28 * 28,)),
        layers.Dense(10, activation="softmax"),
    ]
)



model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

# Fit the model using:
# - train images, train labels
# - 5 epochs
# - 128 batch size
model.fit(train_images, train_labels, epochs=5, batch_size=128)

"""#### Reimplementing our first example from scratch

##### A simple Dense class
"""

import keras
from keras import ops

class NaiveDense:
    def __init__(self, input_size, output_size, activation=None):
        self.activation = activation
        self.W = keras.Variable(
            # Creates a matrix W of shape (input_size, output_size),
            # initialized with random values drawn from a uniform
            # distribution
            shape=(input_size, output_size), initializer="uniform"
        )
        # Creates a vector b of shape (output_size,), initialized with
        # zeros
        self.b = keras.Variable(shape=(output_size,), initializer="zeros")

    # Applies the forward pass
    def __call__(self, inputs):
        # use ops.matmul to perform the matrix multiplication
        # between inputs and weight matrix
        x = ops.matmul(inputs, self.W)
        # add bias term
        x = x + self.b
        if self.activation is not None:
            x = self.activation(x)
        return x

    @property
    # The convenience method for retrieving the layer's weights
    def weights(self):
        return [self.W, self.b]

"""##### A simple Sequential class"""

class NaiveSequential:
    def __init__(self, layers):
        self.layers = layers

    def __call__(self, inputs):
        x = inputs
        for layer in self.layers:
            x = layer(x)
        return x

    @property
    def weights(self):
        weights = []
        for layer in self.layers:
            # for every layer add its weights to weights list
            weights.extend(layer.weights)
        return weights

model = NaiveSequential(
    [
        NaiveDense(input_size=28 * 28, output_size=512, activation=ops.relu),
        NaiveDense(input_size=512, output_size=10, activation=ops.softmax),
    ]
)
assert len(model.weights) == 4

"""##### A batch generator"""

import math

class BatchGenerator:
    def __init__(self, images, labels, batch_size=128):
        assert len(images) == len(labels)
        self.index = 0
        self.images = images
        self.labels = labels
        self.batch_size = batch_size
        self.num_batches = math.ceil(len(images) / batch_size)

    def next(self):
        images = self.images[self.index : self.index + self.batch_size]
        labels = self.labels[self.index : self.index + self.batch_size]
        self.index += self.batch_size
        return images, labels

"""#### Running one training step

##### The weight update step
"""

learning_rate = 1e-3

def update_weights(gradients, weights):
    for g, w in zip(gradients, weights):
        w.assign(w - g * learning_rate)

from keras import optimizers

optimizer = optimizers.SGD(learning_rate=1e-3)

def update_weights(gradients, weights):
    optimizer.apply_gradients(zip(gradients, weights))

"""##### Gradient computation"""

# Commented out IPython magic to ensure Python compatibility.
# %%backend tensorflow
# import tensorflow as tf
# 
# # Instantiates a scalar tensor with value 0
# x = tf.zeros(shape=())
# # Opens a GradientTape scope
# with tf.GradientTape() as tape:
#     # Inside the scope, applies some tensor operations to our variable
#     y = 2 * x + 3
# # Uses the tape to retrieve the gradient of the output y with respect
# # to our variable x
# grad_of_y_wrt_x = tape.gradient(y, x)

# Commented out IPython magic to ensure Python compatibility.
# %%backend tensorflow
# def one_training_step(model, images_batch, labels_batch):
#     with tf.GradientTape() as tape:
#         predictions = model(images_batch)
#         loss = ops.sparse_categorical_crossentropy(labels_batch, predictions)
#         average_loss = ops.mean(loss)
#     gradients = tape.gradient(average_loss, model.weights)
#     update_weights(gradients, model.weights)
#     return average_loss

"""#### The full training loop"""

# Commented out IPython magic to ensure Python compatibility.
# %%backend tensorflow
# def fit(model, images, labels, epochs, batch_size=128):
#     for epoch_counter in range(epochs):
#         print(f"Epoch {epoch_counter}")
#         # create a BatchGenerator instance with images, labels
#         batch_generator = BatchGenerator(images, labels, batch_size)
#         for batch_counter in range(batch_generator.num_batches):
#             images_batch, labels_batch = batch_generator.next()
#             # call one_training_step defined above
#             loss = one_training_step(model, images_batch, labels_batch)
#             if batch_counter % 100 == 0:
#                 print(f"loss at batch {batch_counter}: {loss:.2f}")

# Commented out IPython magic to ensure Python compatibility.
# %%backend tensorflow
# from keras.datasets import mnist
# 
# (train_images, train_labels), (test_images, test_labels) = mnist.load_data()
# 
# train_images = train_images.reshape((60000, 28 * 28))
# train_images = train_images.astype("float32") / 255
# test_images = test_images.reshape((10000, 28 * 28))
# test_images = test_images.astype("float32") / 255
# 
# fit(model, train_images, train_labels, epochs=10, batch_size=128)

"""#### Evaluating the model"""

# Commented out IPython magic to ensure Python compatibility.
# %%backend tensorflow
# predictions = model(test_images)
# predicted_labels = ops.argmax(predictions, axis=1)
# matches = predicted_labels == test_labels
# f"accuracy: {ops.mean(matches):.2f}"